blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostListAllView,
    PostSearchView,
    CategoryListView,
    CategoryFilterView,
)

urlpatterns = [
    path('blog/', PostListView.as_view(), name='blog'),
    path('blog/search/', PostSearchView.as_view(), name='blog-search'),
    path('blog/all/', PostListAllView.as_view(), name='post-list-all'),
    path('blog/categories/', CategoryListView.as_view(), name='category-list'),
    path('blog/categories/filter/',
         CategoryFilterView.as_view(), name='category-filter'),
    path('blog/<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
]

inventory_receiving/urls.py
"""
URL configuration for the inventory_receiving app.
"""
from django.urls import path
from . import views

app_name = 'inventory_receiving'

urlpatterns = [
    # Dashboard
    path('', views.DashboardView.as_view(), name='dashboard'),
    
    # Product Type URLs
    path('product-types/', views.ProductTypeListView.as_view(), name='product_type_list'),
    path('product-types/create/', views.ProductTypeCreateView.as_view(), name='product_type_create'),
    path('product-types/<int:pk>/', views.ProductTypeDetailView.as_view(), name='product_type_detail'),
    path('product-types/<int:pk>/edit/', views.ProductTypeUpdateView.as_view(), name='product_type_edit'),
    
    # Product URLs
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('products/create/', views.ProductCreateView.as_view(), name='product_create'),
    path('products/<slug:sku>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/<slug:sku>/edit/', views.ProductUpdateView.as_view(), name='product_edit'),
    path('products/<slug:sku>/delete/', views.ProductDeleteView.as_view(), name='product_delete'),
    
    # Product Image URLs
    path('products/<slug:sku>/images/add/', views.ProductImageCreateView.as_view(), name='product_image_create'),
    path('images/<int:pk>/delete/', views.ProductImageDeleteView.as_view(), name='product_image_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
# from rest_framework_simplejwt.views import (
#     TokenObtainPairView,
#     TokenRefreshView,
# )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('sendemail.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('blog.urls')),
    path('', include('tasks.urls')),
    path('', include('todo.urls')),
    path('', include('users.urls')),
    path('api-auth', include('rest_framework.urls')),
    # path('api/tasks/v1/rest-auth/', include('rest_auth.urls')),
    # path('api/tasks/v1/rest-auth/registration/', include('rest_auth.registration.urls')),
    # path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('inventory-receiving/', include('inventory_receiving.urls')),
]

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- preload -->
    {% block preload %}{% endblock preload %}
    <link rel="preload" as="image" href="{% static 'images/m_p_logo_58.png' %}" />
    <link rel="preload" as="style" href="{% static 'css/lib/bootstrap.custom.min.css' %}" />
    <link rel="preload" as="style" href="{% static 'css/lib/hamburgers.custom.min.css' %}" />
    <link rel="preload" as="style" href="{% static 'css/lib/animate.custom.min.css' %}" />
    <link rel="preload" as="style" href="{% static 'css/base.css' %}" />

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async nonce="{{ nonce }}" src="https://www.googletagmanager.com/gtag/js?id=G-8T0FQHFQMD"></script>
    <script nonce="{{ nonce }}" src="{% static 'js/analytics.js' %}"></script>

    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    {% block meta_description %}{% endblock meta_description %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/lib/bootstrap.custom.min.css' %}" />

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/m_p_favicon.png' %}" />

    <!-- hamburgers -->
    <link rel="stylesheet" href="{% static 'css/lib/hamburgers.custom.min.css' %}" />

    <!-- animate css -->
    <link rel="stylesheet" href="{% static 'css/lib/animate.custom.min.css' %}" />

    <!-- Google Fonts -->
    <!-- none -->

    <!-- base css -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />

    {% block head_links %}{% endblock head_links %}

    <!-- prettier-ignore -->
    <title>
        {% if title and post.title %}
        {{ title }}: {{ post.title }} -
        {% elif title %}
        {{ title }} -
        {% elif post.title %}
        {{ post.title }} -
        {% endif %}
        Mike Patterson - Web Developer
    </title>

    <!-- json ld -->
    {% block json_ld %}{% endblock json_ld %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img id="nav-brand" src="{% static 'images/m_p_logo_58.png' %}" width="50" height="50"
                    alt="Mike Patterson" />
            </a>
            <button class="navbar-toggler hamburger hamburger--slider animate__animated animate__rubberBand"
                type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <!-- <span class="navbar-toggler-icon"></span> -->
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto pb-3 pb-md-0">
                    <li class="nav-item ps-3 ps-md-0 ms-3 ms-md-0">
                        <a class="nav-link {{ home_active }}" aria-current="{{ home_aria_current|default:'false' }}"
                            href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item ps-3 ps-md-0 ms-3 ms-md-0">
                        <a class="nav-link {{ about_active }}" aria-current="{{ about_aria_current|default:'false' }}"
                            href="{% url 'about' %}">About</a>
                    </li>
                    <li class="nav-item ps-3 ps-md-0 ms-3 ms-md-0">
                        <a class="nav-link {{ projects_active }}"
                            aria-current="{{ projects_aria_current|default:'false' }}"
                            href="{% url 'projects' %}">Projects</a>
                    </li>
                    <li class="nav-item ps-3 ps-md-0 ms-3 ms-md-0">
                        <a class="nav-link {{ contact_active }}"
                            aria-current="{{ contact_aria_current|default:'false' }}"
                            href="{% url 'contact' %}">Contact</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle ps-3 ps-md-2 ms-3 ms-md-0" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Blog
                        </a>
                        <ul class="dropdown-menu mt-3 mt-md-0" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'blog' %}">Recent Posts</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'post-list-all' %}">All Posts</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'category-list' %}">Categories</a>
                            </li>
                            {% if user.is_staff %}
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            <li>
                                <a class="dropdown-item" href="/admin/blog/post/add">New Post</a>
                            </li>

                            {% if post %}
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            <li>
                                <a class="dropdown-item" href="/admin/blog/post/{{ post.pk }}/change/">Edit Post</a>
                            </li>
                            {% endif %}

                            {% endif %}
                        </ul>
                    </li>
                </ul>    
                <ul class="navbar-nav pb-3 pb-md-0">    
                    <li class="nav-item ps-3 ps-md-0 ms-3 ms-md-0">
                        <p class="nav-link mb-0 ms-auto me-1">Hello, {{ user.username|default:"Guest" }}!</p>
                    </li>

                    {% if not user.is_authenticated %}
                    <li class="nav-item ps-3 ps-md-0 ms-3 ms-md-0">
                        <a class="nav-link ps-3 ps-md-2 ms-3 ms-md-0" href="{% url 'login' %}">
                            Login
                        </a>
                    </li>
                    {% endif %}

                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle ps-3 ps-md-2 ms-3 ms-md-0" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            User Menu
                        </a>
                        <ul class="dropdown-menu mt-3 mt-md-0" aria-labelledby="navbarDropdown">
                            {% if perms.inventory_receiving.view_product %}
                            <li>
                                <a class="dropdown-item" href="{% url 'inventory_receiving:dashboard' %}">Inventory Receiving</a>
                            </li>
                            {% endif %}
                            {% if not perms.inventory_receiving.view_product %}
                            <li>
                                <a class="dropdown-item" href="{% url 'contact' %}">Contact Admin to <br> Request Permissions</a>
                            </li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'dashboard' %}">User Dashboard</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            {% if user.is_staff %}
                            <li>
                                <a class="dropdown-item" href="{% url 'admin:index' %}">Admin Site</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            {% endif %}
                            <li class="text-center">
                                <form method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button class="btn btn-outline-danger" type="submit">Log Out</button>
                                </form>
                            </li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>

                <div class="ms-4">
                    <form method="GET" action="/blog/search/" class="d-flex input-group">
                        <input class="form-control" type="search" placeholder="Blog Search" aria-label="Blog Search"
                            aria-describedby="basic-addon2" name="q" value="{{ request.GET.q }}" />
                        <button class="btn btn-outline-primary input-group-text" id="basic-addon2" type="submit">
                            Search
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </nav>

    {% block header %}
    <div class="container">
        <h1 class="py-3 main-heading">{% if title %}{{ title }}{% elif post.title %}{{ post.title }}{% endif %}</h1>
    </div>
    {% endblock header %}

    <div class="flex-column-space-between">
        {% block content %}{% endblock content %}

        <footer>
            <a href="https://www.linkedin.com/in/mike-patterson-web-developer/" target="_blank">LinkedIn</a>
            <span>&bull;</span>
            <a href="https://github.com/mppatterson84" target="_blank">GitHub</a>
        </footer>
    </div>


    <!-- Bootstrap JavaScript -->
    <script nonce="{{ nonce }}" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    {% block foot_links %}{% endblock foot_links %}
    <!-- base js -->
    <script nonce="{{ nonce }}" type="text/javascript" src="{% static 'js/base.js' %}"></script>
</body>

</html>